spring.application.name=MediCore_API
server.port=8080

# Cấu hình MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medicore_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=080306@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate tự tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tắt cảnh báo open-in-view dư thừa
spring.jpa.open-in-view=false